### ISSUE TITLE
Performance Roadmap

### ISSUE THREAD

**Issue by mikeric** [mikeric/rivets#157]
This issue is a place to log some possible optimizations that could be made to improve general performance. Solutions that require changes in existing APIs are also welcome, as most of these will be released as part of **0.6.0**.
- [ ] Avoid redundant re-computing of properties
- [ ] ~~Temporal dirty tracking~~
- [x] Improve the each-\* binder's routine performance
### Avoid redundant re-computing of properties

Say you have a large list of `i` items, and each item in the list contains `n` nodes that are bound to a somewhat expensive computed property. Once a dependency for that computed property changes, rivets will be recomputing that same function `i * n` times, just to set the new value on each list item, even though the returned value of the function (as far as rivets is concerned) will be the same until some other dependent property is changed.

One solution is to have rivets keep track of all bindings outside the scope of a `Rivets.View`, so that we can intelligently recompute the function only once, and then call `binding.set(value)` on all the necessary bindings with the new value.
### Temporal dirty tracking

If you're going to be looping over an array of bound models and changing attribute(s) on them, or appending a set of new models to a collection, it's going to be better if those changes are made without updating the UI each time, and only updating the UI at the very end.

Likewise, if you have listeners set up that further change a property once it has been changed, rivets will update the UI for each of those intermediary changes instead of once for the final changed property.

One solution is to expose a function wrapper that executes a block of code with all active bindings disabled, and then a callback to re-enable the bindings again when things are done (we will just need to log the changes somewhere, so that rivets knows what bindings need to be updated and with what values when `done()` is called).

``` coffeescript
rivets.escape (done) ->
  # do some bulk updating.
  list.items.each (item) ->
    item.set on: false

  # tell rivets that you're done so it can
  # go ahead and apply the changes to the
  # UI and continue with live UI updates.
  done()
```

Think of it like Angular's `$scope.$apply` and the done callback is `$scope.@digest`, except that we don't need to do full "dirty checking" of all the values at the end (that's expensive, especially for deep object dirty checking). We can just track the changes as they happen instead of calling the binder's routine, since we are already subscribed to them.

Perhaps exposing functions to start and stop tracking would be sufficient?

``` coffeescript
# tell rivets to start tracking changes
# instead of performing live UI updates.
rivets.startTracking()

# do some bulk updating.
list.items.each (item) ->
  item.set on: false

# tell rivets to stop tracking changes
# and perform live UI updates instead.
rivets.stopTracking()
```
### Improve the each-\* binder's routine performance

Currently in **0.5.2**, the `each-*` binder removes every iterated node along with their bindings and rebuilds the entire thing for each item in the new array. This could be improved greatly by caching the currently iterated bindings along with their index and iterated object. Then perform a comparison so that we only add/remove new or removed items, and change/move items at different indexes. See comment by @terrancesnyder below for implementation details that will be used.
